### PR TITLE
fix(config): add descriptions to JSON schema properties

### PR DESCRIPTION
**Pull request by Keyrxng**
Relates to https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/24

### CODE REVIEW

**Comment by rndquu** [comment]
@Keyrxng Regarding PRs:
- https://github.com/ubiquity-os-marketplace/daemon-pricing/pull/56
- https://github.com/ubiquity-os-marketplace/command-start-stop/pull/94
- https://github.com/ubiquity-os-marketplace/command-query/pull/25
- https://github.com/ubiquity-os-marketplace/daemon-disqualifier/pull/52
- https://github.com/ubiquity-os-marketplace/command-ask/pull/41
- https://github.com/ubiquity-os-marketplace/text-vector-embeddings/pull/49
- https://github.com/ubiquity-os-marketplace/command-wallet/pull/24
- https://github.com/ubiquity-os-marketplace/daemon-merging/pull/30

Could you add parameter examples in the parameter descriptions? Otherwise it's really hard for a partner to grasp what exact values the parameters accept.

**Comment by Keyrxng** [comment]
> @Keyrxng Regarding PRs:
> 
> * [fix(config): add descriptions to JSON schema properties daemon-pricing#56](https://github.com/ubiquity-os-marketplace/daemon-pricing/pull/56)
> * [fix(config): add descriptions to JSON schema properties #94](https://github.com/ubiquity-os-marketplace/command-start-stop/pull/94)
> * [fix(config): add descriptions to JSON schema properties command-query#25](https://github.com/ubiquity-os-marketplace/command-query/pull/25)
> * [fix(config): add descriptions to JSON schema properties daemon-disqualifier#52](https://github.com/ubiquity-os-marketplace/daemon-disqualifier/pull/52)
> * [fix(config): add descriptions to JSON schema properties command-ask#41](https://github.com/ubiquity-os-marketplace/command-ask/pull/41)
> * [fix(config): add descriptions to JSON schema properties text-vector-embeddings#49](https://github.com/ubiquity-os-marketplace/text-vector-embeddings/pull/49)
> * [fix(config): add descriptions to JSON schema properties command-wallet#24](https://github.com/ubiquity-os-marketplace/command-wallet/pull/24)
> * [fix(config): add descriptions to JSON schema properties daemon-merging#30](https://github.com/ubiquity-os-marketplace/daemon-merging/pull/30)
> 
> Could you add parameter examples in the parameter descriptions? Otherwise it's really hard for a partner to grasp what exact values the parameters accept.

Sure, and this example should be displayed inside the tooltip as well?? I don't think it'll be effective to use them as "placeholders" for input areas since we fill those with either A) defaults B) their installed config.

**Comment by rndquu** [comment]
> Sure, and this example should be displayed inside the tooltip as well??

Yes

> I don't think it'll be effective to use them as "placeholders" for input areas since we fill those with either A) defaults B) their installed config.

You mean showing examples in the [description](https://github.com/ubiquity-os-marketplace/command-start-stop/blob/49d7fb0c55d23d1255cada6cb53eb407fc7fc34f/manifest.json#L44) is not effective?

**Comment by Keyrxng** [comment]
> You mean showing examples in the [description](https://github.com/ubiquity-os-marketplace/command-start-stop/blob/49d7fb0c55d23d1255cada6cb53eb407fc7fc34f/manifest.json#L44) is not effective?

No I meant `input.placeholder` like the background text of `input`, `textarea` and things like that.

> > Sure, and this example should be displayed inside the tooltip as well??

> Yes

Yeah no problem

**Comment by Keyrxng** [comment]
Some props don't require an example as they are either:

- boolean
- self-explanatory through either it's name, default or description such as `emptyWalletText`

**Comment by rndquu** [comment]
@Keyrxng The [examples](https://github.com/ubq-testing/automated-merging/blob/18f3254ab6b3a89d06f2c3b992c0da0cdc6a38d9/src/types/plugin-input.ts#L49) key is automatically placed in the [manifest](https://github.com/ubq-testing/automated-merging/blob/18f3254ab6b3a89d06f2c3b992c0da0cdc6a38d9/manifest.json#L55), correct?

**Comment by Keyrxng** [comment]
Yeah https://github.com/ubiquity-os-marketplace/command-start-stop/blob/development/.github/workflows/update-configuration.yml uses https://github.com/ubiquity-os/action-deploy-plugin/blob/e97f622804cc2a1b802ebdb99d640b3293af72d8/action.yml#L134 which should inject it automatically

**Review by gentlementlegen — APPROVED** [review]

**Review by rndquu — APPROVED** [review]

**Pull request merged**
